version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/otamaomar/skillswap-backend:latest
    container_name: skillswap-backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=4000
      - FRONTEND_URL=http://localhost:8000
      - DATABASE_URL=postgres://mora:Omar.2005@db:5432/skillswap_db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=mora
      - DB_PASSWORD=Omar.2005
      - DB_NAME=skillswap_db
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"pg\").Client({connectionString: process.env.DATABASE_URL}).connect().then(()=>process.exit(0)).catch(()=>process.exit(1))'"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: sh -c "npm run migrate && npm start"

  db:
    image: postgres:15
    container_name: skillswap-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mora
      - POSTGRES_PASSWORD=Omar.2005
      - POSTGRES_DB=skillswap_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mora -d skillswap_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
